### PR TITLE
Fixes #248 Out of range bug

### LINKED ISSUE #248: Should not let user select ayah past end of Surah
For example /1/8 is not possible.

### PR DESCRIPTION
**Pull request by abiodun0**
Handles invalid surah by creating onEnter #248
Creates an error container

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -13,3 +13,4 @@ tests/functional/output/*
 test/functional/screenshots/*
 .ssh
 webpack-stats.debug.json
+.env
```
Comment (mmahalwy) [inline .gitignore]: Hmm, don't need this. We do need `.env` to be committed

File: src/containers/Error/index.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
+import React, { Component } from 'react';
+import IndexHeader from '../../components/IndexHeader';
+import Link from 'react-router/lib/Link';
+import Helmet from 'react-helmet';
+
+export default ({params}) => {
+    console.log(params, 'params?');
```
Comment (mmahalwy) [inline src/containers/Error/index.js]: ✂️

File: src/containers/Home/index.js [hunk 3]
```diff
@@ -141,6 +141,14 @@ class Home extends React.Component {
               Ayat Al-Kursi
             </Link>
           </li>
+          <li>
+            <Link
```
Comment (mmahalwy) [inline src/containers/Home/index.js]: ✂️

File: src/routes.js [hunk 4]
```diff
@@ -16,10 +18,12 @@ export default () => {
 
       <Route path="/contact" getComponent={(nextState, cb) => System.import('./containers/Contact').then(module => cb(null, module))} />
       <Route path="/contactus" getComponent={(nextState, cb) => System.import('./containers/Contact').then(module => cb(null, module))} />
+      <Route path="/error/:errorTitle" getComponent={(nextState, cb) => System.import('./containers/Error').then(module => cb(null, module))} />
 
       <Route path="/search" getComponent={(nextState, cb) => System.import('./containers/Search').then(module => cb(null, module))} />
 
-      <Route path="/:surahId(/:range)" getComponent={(nextState, cb) => System.import('./containers/Surah').then(module => cb(null, module)).catch(err => console.trace(err))} />
+      <Route path="/:surahId(/:range)" getComponent={(nextState, cb) => System.import('./containers/Surah').then(module => cb(null, module)).catch(err => console.trace(err))}
+      onEnter={checkValidSurah} />
```
Comment (mmahalwy) [inline src/routes.js]: nice!

File: src/containers/Error/index.js [hunk 5]
```diff
@@ -0,0 +1,23 @@
+import React, { Component } from 'react';
```
Comment (mmahalwy) [inline src/containers/Error/index.js]: This component is awesome! What I'd recommend, because I assume we'd want to reuse it for other errors, is having `:errorTitle` be a key to return text given THAT error. For example, `/errors/out-of-range` would then return `'s an invalid Surah/Ayah. Please go to the <a href="/">home page </a>and select a surah'` and say `/errors/some-other-error` would return that text.

Comment (abiodun0) [inline src/containers/Error/index.js]: That is exactly what this component does. Maybe errorTitle isn't exactly the name to use should I use `errorText`?

File: src/containers/Error/index.js [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+  }
+    return (
+      <div>
+        <Helmet title={`Error ${params.errorTitle}`} />
+        <IndexHeader noSearch={true} />
+        <div className="container-fluid about-text">
+          <div className="row">
+              <div className="col-md-8 col-md-offset-2">
+                  <h4 className="source-sans">
+                    {error[params.errorKey]}. Please go to the <a href="/">home page </a>and select a surah/Ayah
```
Comment (mmahalwy) [inline src/containers/Error/index.js]: `Surah` capitalized :)

File: src/containers/Error/index.js [hunk 7]
```diff
@@ -0,0 +1,26 @@
+import React, { Component } from 'react';
+import IndexHeader from '../../components/IndexHeader';
+import Link from 'react-router/lib/Link';
+import Helmet from 'react-helmet';
+
+export default ({params}) => {
+  const error = {
```
Comment (mmahalwy) [inline src/containers/Error/index.js]: Alignment is off?

File: src/containers/Home/index.js [hunk 8]
```diff
@@ -141,6 +141,14 @@ class Home extends React.Component {
               Ayat Al-Kursi
             </Link>
           </li>
+          <li>
```
Comment (mmahalwy) [inline src/containers/Home/index.js]: ✂️ ✂️ ✂️ ✂️ ✂️ ✂️ ✂️  This link is invalid :)
